ALTER TABLE "TrackerUser"
  ADD COLUMN IF NOT EXISTS "displayName" TEXT,
  ADD COLUMN IF NOT EXISTS "collectionSlug" TEXT,
  ADD COLUMN IF NOT EXISTS "collectionTitle" TEXT,
  ADD COLUMN IF NOT EXISTS "collectionBio" TEXT,
  ADD COLUMN IF NOT EXISTS "collectionPublished" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS "TrackerUser_collectionSlug_key"
  ON "TrackerUser"("collectionSlug");

ALTER TABLE "TrackerItem"
  ADD COLUMN IF NOT EXISTS "inCollection" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "acquiredAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "condition" TEXT,
  ADD COLUMN IF NOT EXISTS "purchasePrice" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "purchaseCurrency" TEXT,
  ADD COLUMN IF NOT EXISTS "showPurchasePrice" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "switches" TEXT,
  ADD COLUMN IF NOT EXISTS "keycaps" TEXT,
  ADD COLUMN IF NOT EXISTS "buildDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "notes" TEXT,
  ADD COLUMN IF NOT EXISTS "displayOrder" INTEGER NOT NULL DEFAULT 0;
